name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install numdiff
      run: sudo apt install -y numdiff

    - name: Configure CMake Gauss-Seidel
      run: >
        cmake -B ${{github.workspace}}/build-gs
        -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -D CMAKE_C_COMPILER=gcc
        -D CMAKE_CXX_COMPILER=g++
        -D USEGS=ON

    - name: Configure CMake LAPACK
      run: >
        cmake -B ${{github.workspace}}/build-lp
        -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -D CMAKE_C_COMPILER=gcc
        -D CMAKE_CXX_COMPILER=g++
        -D USEGS=OFF

    - name: Compile Gauss-Seidel
      run: cmake --build ${{github.workspace}}/build-gs --config ${{env.BUILD_TYPE}}

    - name: Compile LAPACK
      run: cmake --build ${{github.workspace}}/build-lp --config ${{env.BUILD_TYPE}}

    - name: Test Gauss-Seidel
      working-directory: ${{github.workspace}}/build-gs
      run: ctest -V

    - name: Test LAPACK
      working-directory: ${{github.workspace}}/build-lp
      run: ctest -V
